name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # midnight, every day

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Linter
      run: cargo fmt --all -- --check

    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true

    - name: Build (Default)
      run: |
        cargo build
    
    - name: Build (All features)
      run: |
        cargo build --all-features
    
    - name: Build (BINEX)
      run: |
        cargo build --no-default-features --features binex
    
    - name: Build (GPS)
      run: |
        cargo build --no-default-features --features gps
    
    - name: Build (QZSS)
      run: |
        cargo build --no-default-features --features qzss
    
    - name: Build (RTCM)
      run: |
        cargo build --no-default-features --features rtcm
    
    - name: Build (UBX)
      run: |
        cargo build --no-default-features --features ubx
